apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  ports: 
    - port: 3050
    # targetPort is where app is listening
      targetPort: 80
    # nodeport is ip-address colon port
      nodePort: 31010
  selector:
    component: web